spring:
  profiles:
    active: local
---
spring:
  profiles: local
  jpa:
    database: H2
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:h2:file:/Users/kbastani/test1.db"
    username: ""
    password: ""